spring:
  application:
    name: post-api
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/subhakarcode?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: subhakar